name: Build

on:
  push:
    paths-ignore:
      - "docs/**"
      - "logo/**"
      - "examples/**"
      - "README.md"
    branches:
      - "master"

  pull_request:
    branches:
      - "master"
      - "feat/*"
      - "fix/*"

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: GoogleContainerTools/skaffold
          tag: v1.38.0
          cache: enable
          extension-matching: disable
          rename-to: skaffold
          chmod: 0755
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: "1.17.7"
      - run: |
          go install honnef.co/go/tools/cmd/staticcheck@2022.1.3
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: just lint
      - run: just test
      - uses: rinx/setup-k3d@v0.0.4
        with:
          skipClusterCreation: true
      - run: just k3d
      - run: pip install httpie
      - run: |
          just test-e2e-all
      - name: failure logs
        if: ${{ failure() }}
        run: |
          echo "------------------------------------------------------------------------------------------------------------------"
          kubectl get all -A
          echo "------------------------------------------------------------------------------------------------------------------"
          # CHART=$(basename `pwd`)
          # for NS in $(kubectl get ns --no-headers -o custom-columns=:metadata.name); do
          #   echo "Namespace: ${NS}"
          #   echo "------------------------------------------------------------------------------------------------------------------"
          #   kubectl logs -l app.kubernetes.io/name=${CHART} -n ${NS} --tail=-1
          #   echo "------------------------------------------------------------------------------------------------------------------"
          #   echo ""
          # done
          # echo "------------------------------------------------------------------------------------------------------------------"
          # kubectl describe po $CHART || true
          # echo "------------------------------------------------------------------------------------------------------------------"
